import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import { ActivityIndicator, AppState, FlatList, KeyboardAvoidingView, Platform, Pressable, StyleSheet, Text, View } from 'react-native'
import { Stack, useFocusEffect, useLocalSearchParams } from 'expo-router'
import type { Message } from '../../src/lib/types'
import { useStore } from '../../src/store'
import { cmpId, sameDay, withinMinutes } from '../../src/lib/util'
import { Avatar } from '../../src/components/Avatar'
import { DayDivider } from '../../src/components/DayDivider'
import { MessageItem } from '../../src/components/MessageItem'
import { Composer } from '../../src/components/Composer'
import { ChatLayoutChooser } from '../../src/components/ChatLayoutChooser'
type Row = { type: 'message'; message: Message; grouped: boolean } | { type: 'day'; id: string; iso: string }
export default function ChannelScreen() {
  const { id } = useLocalSearchParams<{ id: string }>(); const channel = useStore((s) => s.channels.find((c) => c.id === id)); const cm = useStore((s) => id ? s.byChannel[id] : undefined); const me = useStore((s) => s.me); const online = useStore((s) => s.online); const layout = useStore((s) => s.chatLayout); const setLayout = useStore((s) => s.setChatLayout); const setCurrent = useStore((s) => s.setCurrentChannel); const load = useStore((s) => s.loadMessages); const older = useStore((s) => s.loadOlder); const markRead = useStore((s) => s.markRead)
  const atBottom = useRef(true); const readTimer = useRef<ReturnType<typeof setTimeout> | null>(null); const [active, setActive] = useState(AppState.currentState === 'active'); const muted = useStore((s) => id ? s.mutedChannels.has(id) : false); const toggleMute = useStore((s) => s.toggleMute)
  useFocusEffect(useCallback(() => { if (!id) return; setCurrent(id); if (!useStore.getState().byChannel[id]?.loaded) void load(id); return () => setCurrent(null) }, [id, load, setCurrent]))
  useEffect(() => { const sub = AppState.addEventListener('change', (next) => setActive(next === 'active')); return () => sub.remove() }, [])
  const messages = useMemo(() => [...(cm?.list ?? [])].sort((a,b) => cmpId(b.id, a.id)), [cm?.list])
  const newest = messages[0]?.id
  const rows = useMemo<Row[]>(() => messages.flatMap((m, i) => { const newer = messages[i - 1]; const grouped = !!newer && sameDay(newer.created_at, m.created_at) && newer.user.id === m.user.id && withinMinutes(newer.created_at, m.created_at, 5) && !newer.deleted_at; const nextOlder = messages[i + 1]; return [{ type: 'message' as const, message: m, grouped }, ...(!nextOlder || !sameDay(m.created_at, nextOlder.created_at) ? [{ type: 'day' as const, id: `day-${m.id}`, iso: m.created_at }] : [])] }), [messages])
  const keyExtractor = useCallback((row: Row) => row.type === 'message' ? row.message.id : row.id, [])
  const renderItem = useCallback(({ item }: { item: Row }) => item.type === 'day' ? <DayDivider iso={item.iso}/> : <MessageItem message={item.message} grouped={item.grouped} bubble={channel?.kind === 'dm' && layout === 'bubble'} mine={item.message.user.id === me?.id} online={channel?.kind !== 'dm' && online.has(item.message.user.id)} />, [channel?.kind, layout, me?.id, online])
  const scheduleRead = useCallback(() => { if (!id || !newest || !active || !atBottom.current) return; if (readTimer.current) clearTimeout(readTimer.current); readTimer.current = setTimeout(() => { if (AppState.currentState === 'active' && atBottom.current) markRead(id, newest) }, 400) }, [active, id, markRead, newest])
  useEffect(() => { scheduleRead(); return () => { if (readTimer.current) clearTimeout(readTimer.current) } }, [scheduleRead])
  if (!channel) return <View style={styles.center}><Text>Channel not found.</Text></View>
  const dm = channel.kind === 'dm'; const title = dm ? channel.dm_user?.display_name ?? 'Direct message' : `${channel.kind === 'private' ? '🔒 ' : '#'}${channel.name}`
  return <KeyboardAvoidingView style={styles.page} behavior={Platform.OS === 'ios' ? 'padding' : undefined} keyboardVerticalOffset={88}><Stack.Screen options={{ headerShown: true, title, headerRight: () => <View style={{ flexDirection: 'row', alignItems: 'center', gap: 10 }}>{dm && channel.dm_user ? <Avatar id={channel.dm_user.id} name={channel.dm_user.display_name} url={channel.dm_user.avatar_url} size={28} online={online.has(channel.dm_user.id)} /> : null}<Pressable accessibilityLabel={muted ? 'Unmute channel' : 'Mute channel'} onPress={() => void toggleMute(channel.id)}><Text style={{ fontSize: 19 }}>{muted ? '🔕' : '🔔'}</Text></Pressable></View> }}/>{channel.topic && !dm && <Text style={styles.topic}>{channel.topic}</Text>}<FlatList inverted data={rows} keyExtractor={keyExtractor} maintainVisibleContentPosition={{ minIndexForVisible: 0 }} onEndReached={() => { if (id) void older(id) }} onEndReachedThreshold={.2} onScroll={(e) => { atBottom.current = e.nativeEvent.contentOffset.y < 80; if (atBottom.current) scheduleRead() }} scrollEventThrottle={16} renderItem={renderItem} ListHeaderComponent={cm?.hasMore ? <View style={styles.loading}>{cm.loading ? <ActivityIndicator/> : <Text style={styles.hint}>Pull for earlier messages</Text>}</View> : null} ListEmptyComponent={cm?.loading ? <ActivityIndicator style={{ marginTop: 30 }}/> : <Text style={styles.empty}>This is the start of the conversation.</Text>} contentContainerStyle={styles.list}/><Typing channelId={id}/><Composer channel={channel} placeholder={`Message ${dm ? title : '#' + channel.name}`}/>{dm && layout === null ? <ChatLayoutChooser onChoose={setLayout}/> : null}</KeyboardAvoidingView>
}
function Typing({ channelId }: { channelId: string }) { const typing = useStore((s) => s.typing[channelId]); const names = Object.values(typing ?? {}).map((x) => x.display_name); const text = names.length === 1 ? `${names[0]} is typing…` : names.length === 2 ? `${names[0]} and ${names[1]} are typing…` : names.length > 2 ? `${names.length} people are typing…` : ''; return <View style={styles.typing}><Text>{text}</Text></View> }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: 'white' }, topic: { paddingHorizontal: 16, paddingVertical: 7, color: '#667085', fontSize: 13, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#d8dce3' }, list: { paddingTop: 8, paddingBottom: 12 }, loading: { padding: 14, alignItems: 'center' }, hint: { color: '#667085', fontSize: 12 }, empty: { color: '#667085', textAlign: 'center', marginTop: 50 }, typing: { height: 24, paddingHorizontal: 16, justifyContent: 'center' }, composer: { borderTopWidth: StyleSheet.hairlineWidth, borderColor: '#d8dce3', padding: 10 }, input: { height: 42, borderWidth: 1, borderColor: '#d0d5dd', borderRadius: 10, paddingHorizontal: 12, backgroundColor: '#f9fafb' }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' } })
