import { memo, useState } from 'react'
import { Alert, Modal, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { router } from 'expo-router'
import * as Clipboard from 'expo-clipboard'
import type { Message } from '../lib/types'
import { fmtTime, stripResourceTokens } from '../lib/util'
import { Avatar } from './Avatar'
import { Attachment } from './Attachment'
import { selectDisplayNames, useStore } from '../store'
import { Markdown } from './Markdown'

const readable = stripResourceTokens
export const MessageItem = memo(function MessageItem({ message, grouped, bubble, mine, online, showThread = true }: { message: Message; grouped: boolean; bubble: boolean; mine: boolean; online?: boolean; showThread?: boolean }) {
  const [actions, setActions] = useState(false); const [editing, setEditing] = useState(false); const [draft, setDraft] = useState(message.content)
  const toggleReaction = useStore((s) => s.toggleReaction); const editMessage = useStore((s) => s.editMessage); const deleteMessage = useStore((s) => s.deleteMessage); const setReply = useStore((s) => s.setReplyTarget); const requestFocus = useStore((s) => s.requestComposerFocus)
  const users = useStore((s) => s.users)
  const names = selectDisplayNames(users)
  const action = (fn: () => void) => { setActions(false); fn() }
  const body = message.deleted_at ? <Text style={styles.deleted}>message deleted</Text> : <><>{message.reply_to && <View style={styles.quote}><Text style={styles.quoteAuthor}>{message.reply_to.user.display_name}</Text><Text style={styles.quoteText} numberOfLines={2}>{message.reply_to.deleted ? 'message deleted' : readable(message.reply_to.content)}</Text></View>}</><Markdown content={message.content} names={names}/>{message.edited_at ? <Text style={styles.edited}> (edited)</Text> : null}{message.attachments.map((a) => <Attachment key={a.id} attachment={a}/>)}</>
  const extras = !message.deleted_at && <><View style={styles.reactions}>{message.reactions.map((r) => <Pressable onPress={() => void toggleReaction(message, r.emoji)} key={r.emoji} style={[styles.reaction, r.me && styles.reactionMe]}><Text>{r.emoji} {r.count}</Text></Pressable>)}</View>{showThread && message.reply_count > 0 && <Pressable onPress={() => router.push(`/thread/${message.id}`)} style={styles.thread}><Text style={styles.threadText}>{message.reply_count} {message.reply_count === 1 ? 'reply' : 'replies'}{message.last_reply_at ? ` · ${fmtTime(message.last_reply_at)}` : ''}</Text></Pressable>}</>
  const editor = editing ? <View style={styles.editor}><TextInput multiline value={draft} onChangeText={setDraft} style={styles.editInput}/><View style={styles.editButtons}><Pressable onPress={() => { if (draft.trim()) void editMessage(message.id, draft.trim()).then(() => setEditing(false)) }}><Text style={styles.save}>Save</Text></Pressable><Pressable onPress={() => setEditing(false)}><Text>Cancel</Text></Pressable></View></View> : body
  const content = bubble ? <View style={[styles.bubbleRow, mine ? styles.mine : styles.other]}><Pressable onLongPress={() => setActions(true)} style={[styles.bubble, mine ? styles.mineBubble : styles.otherBubble]}>{editor}<Text style={styles.bubbleTime}>{fmtTime(message.created_at)}</Text></Pressable>{extras}</View> : <Pressable onLongPress={() => setActions(true)} style={[styles.classic, grouped && styles.grouped]}><View style={styles.gutter}>{!grouped && <Avatar id={message.user.id} name={message.user.display_name} url={message.user.avatar_url} online={online} />}</View><View style={styles.messageMain}>{!grouped && <View style={styles.meta}><Text style={styles.name}>{message.user.display_name}</Text><Text style={styles.time}>{fmtTime(message.created_at)}</Text></View>}{editor}{extras}</View></Pressable>
  return <>{content}<Modal visible={actions} transparent animationType="slide" onRequestClose={() => setActions(false)}><Pressable style={styles.scrim} onPress={() => setActions(false)}><View style={styles.sheet}><Text style={styles.sheetTitle}>Message actions</Text><View style={styles.emoji}>{['👍','✅','👀','❤️','😂','🎉'].map((e) => <Pressable key={e} onPress={() => action(() => void toggleReaction(message, e))} style={styles.emojiBtn}><Text>{e}</Text></Pressable>)}</View><Action label="Reply" onPress={() => action(() => { setReply(message.channel_id, message); requestFocus(`c:${message.channel_id}`) })}/>{showThread && <Action label="Reply in thread" onPress={() => action(() => router.push(`/thread/${message.parent_id ?? message.id}`))}/>}<Action label="Copy text" onPress={() => action(() => void Clipboard.setStringAsync(message.content))}/>{mine && !message.deleted_at && <><Action label="Edit" onPress={() => action(() => { setDraft(message.content); setEditing(true) })}/><Action label="Delete" danger onPress={() => action(() => Alert.alert('Delete message?', 'This cannot be undone.', [{ text: 'Cancel', style: 'cancel' }, { text: 'Delete', style: 'destructive', onPress: () => void deleteMessage(message.id) }]))}/></>}</View></Pressable></Modal></>
})
function Action({ label, onPress, danger }: { label: string; onPress: () => void; danger?: boolean }) { return <Pressable onPress={onPress} style={styles.action}><Text style={danger && styles.danger}>{label}</Text></Pressable> }
const styles = StyleSheet.create({ classic: { flexDirection: 'row', gap: 10, paddingHorizontal: 16, paddingTop: 9 }, grouped: { paddingTop: 2 }, gutter: { width: 36 }, messageMain: { flex: 1, minWidth: 0 }, meta: { flexDirection: 'row', alignItems: 'baseline', gap: 7 }, name: { fontWeight: '700', fontSize: 14, color: '#101828' }, time: { fontSize: 11, color: '#667085' }, edited: { color: '#667085', fontSize: 12 }, deleted: { fontStyle: 'italic', color: '#667085', marginTop: 3 }, quote: { borderLeftWidth: 3, borderColor: '#98a2b3', paddingLeft: 8, marginTop: 5 }, quoteAuthor: { fontWeight: '700', fontSize: 12, color: '#475467' }, quoteText: { color: '#667085', fontSize: 13 }, reactions: { flexDirection: 'row', flexWrap: 'wrap', gap: 5, marginTop: 6 }, reaction: { borderWidth: 1, borderColor: '#d0d5dd', borderRadius: 14, paddingHorizontal: 8, paddingVertical: 2 }, reactionMe: { borderColor: '#6172f3', backgroundColor: '#eef4ff' }, thread: { alignSelf: 'flex-start', marginTop: 6, paddingHorizontal: 8, paddingVertical: 4, borderRadius: 12, backgroundColor: '#eef4ff' }, threadText: { color: '#444ce7', fontSize: 12, fontWeight: '600' }, bubbleRow: { paddingHorizontal: 14, paddingTop: 6, maxWidth: '86%' }, mine: { alignSelf: 'flex-end', alignItems: 'flex-end' }, other: { alignSelf: 'flex-start', alignItems: 'flex-start' }, bubble: { paddingHorizontal: 11, paddingVertical: 8, borderRadius: 16 }, mineBubble: { backgroundColor: '#e0e7ff', borderBottomRightRadius: 4 }, otherBubble: { backgroundColor: '#f2f4f7', borderBottomLeftRadius: 4 }, bubbleTime: { alignSelf: 'flex-end', color: '#667085', fontSize: 10, marginTop: 3 }, scrim: { flex: 1, justifyContent: 'flex-end', backgroundColor: 'rgba(0,0,0,.35)' }, sheet: { backgroundColor: 'white', padding: 18, borderTopLeftRadius: 18, borderTopRightRadius: 18 }, sheetTitle: { fontWeight: '700', marginBottom: 8 }, emoji: { flexDirection: 'row', justifyContent: 'space-between', marginBottom: 8 }, emojiBtn: { padding: 9 }, action: { paddingVertical: 14, borderTopWidth: StyleSheet.hairlineWidth, borderColor: '#eaecf0' }, danger: { color: '#b42318', fontWeight: '700' }, editor: { marginTop: 5, borderWidth: 1, borderColor: '#6172f3', borderRadius: 8, padding: 7 }, editInput: { minHeight: 70, fontSize: 15 }, editButtons: { flexDirection: 'row', gap: 16, marginTop: 6 }, save: { color: '#444ce7', fontWeight: '700' } })
