import { useCallback } from 'react'
import { FlatList, Pressable, StyleSheet, Switch, Text, View } from 'react-native'
import { useFocusEffect, useRouter } from 'expo-router'
import type { Notification } from '../../src/lib/types'
import { fmtRelative, stripResourceTokens } from '../../src/lib/util'
import { Avatar } from '../../src/components/Avatar'
import { useStore } from '../../src/store'
const label: Record<Notification['kind'], string> = { mention: 'mentioned you', dm: 'messaged you', reply: 'replied to your thread' }
const preview = (text: string) => stripResourceTokens(text).replace(/[*_`~>#]/g, '').replace(/\s+/g, ' ').trim()
export default function ActivityScreen() { const router = useRouter(); const items = useStore((s) => s.notifications); const unread = useStore((s) => s.notifUnread); const more = useStore((s) => s.notifHasMore); const dnd = useStore((s) => s.dnd); const reload = useStore((s) => s.loadInboxAndPrefs); const older = useStore((s) => s.loadMoreNotifications); const read = useStore((s) => s.markNotifRead); const all = useStore((s) => s.markAllNotifRead); const setDnd = useStore((s) => s.setDnd); useFocusEffect(useCallback(() => { void reload() }, [reload])); return <View style={styles.page}><View style={styles.header}><View><Text style={styles.title}>Activity</Text><Text style={styles.sub}>{unread ? `${unread} unread` : 'You’re all caught up'}</Text></View><Pressable disabled={!unread} onPress={all}><Text style={[styles.all, !unread && styles.disabled]}>Mark all read</Text></Pressable></View><View style={styles.dnd}><View><Text style={styles.dndTitle}>Do Not Disturb</Text><Text style={styles.dndSub}>Mute notification alerts</Text></View><Switch value={dnd} onValueChange={(v) => void setDnd(v)} trackColor={{ true: '#6172f3' }}/></View><FlatList data={items} keyExtractor={(n) => n.id} onEndReached={() => { if (more) void older() }} onEndReachedThreshold={.25} renderItem={({ item }) => <Pressable onPress={() => { read(item.id); router.push(`/channel/${item.channel_id}`) }} style={[styles.row, !item.read_at && styles.rowUnread]}><Avatar id={item.actor.id} name={item.actor.display_name} url={item.actor.avatar_url} size={38}/><View style={styles.main}><View style={styles.line}><Text numberOfLines={1} style={styles.actor}>{item.actor.display_name} <Text style={styles.kind}>{label[item.kind]}</Text></Text><Text style={styles.time}>{fmtRelative(item.created_at)}</Text></View>{item.preview ? <Text numberOfLines={2} style={styles.preview}>{preview(item.preview)}</Text> : null}<Text style={styles.channel}>{item.channel_kind === 'dm' ? 'Direct message' : `#${item.channel_name}`}</Text></View>{!item.read_at && <View style={styles.dot}/>}</Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>🔔</Text><Text style={styles.emptyText}>No activity yet</Text><Text style={styles.emptySub}>Mentions and messages will appear here.</Text></View>} ListFooterComponent={more ? <Text style={styles.loading}>Loading older activity…</Text> : null}/></View> }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: 'white' }, header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#eaecf0' }, title: { fontSize: 27, fontWeight: '700', color: '#101828' }, sub: { color: '#667085', marginTop: 2 }, all: { color: '#444ce7', fontWeight: '700', fontSize: 13 }, disabled: { opacity: .35 }, dnd: { margin: 14, padding: 13, borderRadius: 10, backgroundColor: '#f8f9fc', flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' }, dndTitle: { fontWeight: '700', color: '#344054' }, dndSub: { fontSize: 12, color: '#667085', marginTop: 2 }, row: { flexDirection: 'row', gap: 10, padding: 14, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#eaecf0' }, rowUnread: { backgroundColor: '#f5f7ff', borderLeftWidth: 3, borderLeftColor: '#6172f3', paddingLeft: 11 }, main: { flex: 1, minWidth: 0 }, line: { flexDirection: 'row', gap: 8, justifyContent: 'space-between' }, actor: { flex: 1, fontWeight: '700', color: '#344054' }, kind: { fontWeight: '400', color: '#667085' }, time: { fontSize: 11, color: '#98a2b3' }, preview: { marginTop: 3, fontSize: 13, lineHeight: 18, color: '#667085' }, channel: { marginTop: 5, color: '#444ce7', fontSize: 11, fontWeight: '600' }, dot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#6172f3', marginTop: 5 }, empty: { alignItems: 'center', marginTop: 80, gap: 5 }, emptyIcon: { fontSize: 30 }, emptyText: { fontWeight: '700', color: '#475467' }, emptySub: { color: '#98a2b3', fontSize: 13 }, loading: { textAlign: 'center', color: '#667085', padding: 16, fontSize: 12 } })
