import { useMemo } from 'react'
import { RefreshControl, SectionList, StyleSheet, Text, TouchableOpacity, View } from 'react-native'
import { router } from 'expo-router'
import { useStore } from '../../src/store'

export default function ChatsScreen() {
  const channels = useStore((s) => s.channels); const online = useStore((s) => s.online); const muted = useStore((s) => s.mutedChannels); const refetch = useStore((s) => s.refetchDirectory)
  const sections = useMemo(() => [{ title: 'Direct Messages', data: channels.filter((c) => c.kind === 'dm').sort((a, b) => (b.last_message_at ?? '').localeCompare(a.last_message_at ?? '')) }, { title: 'Channels', data: channels.filter((c) => c.kind !== 'dm' && c.is_member).sort((a, b) => a.name.localeCompare(b.name)) }], [channels])
  return <SectionList sections={sections} keyExtractor={(item) => item.id} refreshControl={<RefreshControl refreshing={false} onRefresh={() => void refetch()} />} renderSectionHeader={({ section }) => <Text style={styles.heading}>{section.title}</Text>} renderItem={({ item }) => { const isMuted = muted.has(item.id); const unread = item.unread_count > 0; const dm = item.kind === 'dm'; return <TouchableOpacity style={[styles.row, isMuted && styles.muted]} onPress={() => router.push(`/channel/${item.id}`)} accessibilityLabel={`Open ${dm ? item.dm_user?.display_name : item.name}`}><View style={[styles.presence, { backgroundColor: dm && item.dm_user && online.has(item.dm_user.id) ? '#31a06a' : 'transparent' }]} /><Text style={[styles.prefix, !dm && item.kind === 'private' && styles.lock]}>{dm ? '' : item.kind === 'private' ? '🔒' : '#'}</Text><Text style={[styles.name, unread && !isMuted && styles.unreadName]} numberOfLines={1}>{dm ? item.dm_user?.display_name ?? 'Direct message' : item.name}</Text>{unread && (isMuted ? <View style={styles.unreadDot} /> : <View style={styles.badge}><Text style={styles.badgeText}>{item.unread_count > 99 ? '99+' : item.unread_count}</Text></View>)}</TouchableOpacity> }} ListEmptyComponent={<Text style={styles.empty}>No conversations yet.</Text>} contentContainerStyle={styles.content} />
}
const styles = StyleSheet.create({ content: { paddingVertical: 12 }, heading: { color: '#667085', fontSize: 12, fontWeight: '700', textTransform: 'uppercase', marginTop: 12, marginBottom: 5, paddingHorizontal: 16 }, row: { minHeight: 48, paddingHorizontal: 16, alignItems: 'center', flexDirection: 'row', gap: 8 }, muted: { opacity: .52 }, presence: { width: 8, height: 8, borderRadius: 4 }, prefix: { width: 16, color: '#667085', fontSize: 17 }, lock: { fontSize: 13 }, name: { flex: 1, fontSize: 16, color: '#344054' }, unreadName: { color: '#101828', fontWeight: '700' }, badge: { minWidth: 22, paddingHorizontal: 6, height: 20, borderRadius: 10, alignItems: 'center', justifyContent: 'center', backgroundColor: '#444ce7' }, badgeText: { color: 'white', fontSize: 12, fontWeight: '700' }, unreadDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: '#667085' }, empty: { textAlign: 'center', color: '#667085', marginTop: 40 } })
