import { useEffect, useState } from 'react'
import { ActivityIndicator, FlatList, Pressable, StyleSheet, Text, TextInput, View } from 'react-native'
import { useRouter } from 'expo-router'
import { api } from '../../src/lib/api'
import type { SearchResult } from '../../src/lib/types'
import { fmtRelative } from '../../src/lib/util'
import { Avatar } from '../../src/components/Avatar'
import { Markdown } from '../../src/components/Markdown'
import { selectDisplayNames, useStore } from '../../src/store'
export default function SearchScreen() { const router = useRouter(); const users = useStore((s) => s.users); const [query, setQuery] = useState(''); const [results, setResults] = useState<SearchResult[]>([]); const [loading, setLoading] = useState(false); useEffect(() => { const q = query.trim(); if (q.length < 2) { setResults([]); setLoading(false); return }; let cancelled = false; const timer = setTimeout(() => { setLoading(true); api.search(q).then((r) => !cancelled && setResults(r.results)).catch(() => !cancelled && setResults([])).finally(() => !cancelled && setLoading(false)) }, 300); return () => { cancelled = true; clearTimeout(timer) } }, [query]); const names = selectDisplayNames(users); return <View style={styles.page}><Text style={styles.title}>Search</Text><TextInput autoFocus value={query} onChangeText={setQuery} placeholder="Search messages" style={styles.input}/>{loading ? <ActivityIndicator style={styles.spinner}/> : <FlatList data={results} keyExtractor={(r) => r.id} renderItem={({ item }) => <Pressable onPress={() => router.push(`/channel/${item.channel_id}`)} style={styles.row}><View style={styles.meta}><Text style={styles.channel}>#{item.channel_name}</Text><Text style={styles.time}>{fmtRelative(item.created_at)}</Text></View><View style={styles.content}><Avatar id={item.user.id} name={item.user.display_name} url={item.user.avatar_url} size={30}/><View style={styles.body}><Text style={styles.author}>{item.user.display_name}</Text><Markdown content={item.content} names={names} compact/></View></View></Pressable>} ListEmptyComponent={<View style={styles.empty}><Text style={styles.emptyIcon}>🔍</Text><Text style={styles.emptyText}>{query.trim().length < 2 ? 'Type at least two characters' : 'No messages matched your search.'}</Text></View>}/>}</View> }
const styles = StyleSheet.create({ page: { flex: 1, backgroundColor: 'white', paddingTop: 18 }, title: { paddingHorizontal: 18, fontSize: 27, fontWeight: '700', color: '#101828' }, input: { margin: 14, borderWidth: 1, borderColor: '#d0d5dd', borderRadius: 10, paddingHorizontal: 12, paddingVertical: 10, backgroundColor: '#f9fafb', fontSize: 16 }, spinner: { marginTop: 40 }, row: { marginHorizontal: 14, paddingVertical: 12, borderBottomWidth: StyleSheet.hairlineWidth, borderColor: '#eaecf0' }, meta: { flexDirection: 'row', gap: 8, marginBottom: 6 }, channel: { color: '#444ce7', fontSize: 12, fontWeight: '700' }, time: { color: '#98a2b3', fontSize: 12 }, content: { flexDirection: 'row', gap: 9 }, body: { flex: 1, minWidth: 0 }, author: { fontWeight: '700', fontSize: 13, color: '#344054' }, empty: { alignItems: 'center', marginTop: 75, gap: 7 }, emptyIcon: { fontSize: 30 }, emptyText: { color: '#667085' } })
