-- Garden creator mode: a workspace admin flag and the scenery an admin places.

-- --- Workspace admin -------------------------------------------------------
-- There was no workspace-level role before this. The only role system is
-- channel-scoped (routes/mod.rs::ChannelRole), and the Garden map editor is the
-- first surface that changes something *everyone* sees.
--
-- Deliberately one flag, with the gate in exactly one helper
-- (routes::require_workspace_admin), so widening the definition later — a real
-- roles table, several admins, an env allowlist — is a one-function change and
-- no call site moves.
ALTER TABLE users ADD COLUMN is_admin boolean NOT NULL DEFAULT false;

-- Promote the workspace founder on an existing install. A fresh database has no
-- users, so this is a no-op there and the trigger below handles it instead.
UPDATE users SET is_admin = true
 WHERE id = (SELECT id FROM users ORDER BY created_at, id LIMIT 1);

-- The very first account on a fresh install becomes admin. A trigger rather than
-- route code because there are two signup paths — auth::register and
-- routes::social_auth — and a Google-first install must not end up with no admin
-- and no way to get one. Same shape as allocate_garden_room in 0035.
CREATE OR REPLACE FUNCTION garden_seed_first_admin()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM users) THEN
        NEW.is_admin := true;
    END IF;
    RETURN NEW;
END;
$$;

CREATE TRIGGER users_seed_first_admin
BEFORE INSERT ON users
FOR EACH ROW
EXECUTE FUNCTION garden_seed_first_admin();

-- --- Placed scenery --------------------------------------------------------
-- One row per placed object rather than a snapshot of the world. The default
-- world stays a *function* of the room plots plus a fixed seed
-- (web/src/lib/garden/terrain.ts), so it keeps following the village as channels
-- are created; these rows are the sparse diff an admin paints on top. A snapshot
-- would freeze that default the moment it was first saved.
--
-- The id is generated by the client so an optimistic placement needs no id
-- reconciliation and a replayed op is idempotent.
CREATE TABLE garden_objects (
    id uuid PRIMARY KEY,
    -- Catalogue id. Bounded here; the real allowlist is GARDEN_PROP_IDS in Rust,
    -- so adding a prop is a code change and never a migration.
    kind text NOT NULL CHECK (kind <> '' AND length(kind) <= 40),
    -- Tile coordinates, fractional so scenery can sit on a half tile. Loose
    -- bounds only: the authoritative clamp is in routes/garden.rs against the
    -- same hub dimensions movement already uses, so the two cannot disagree.
    x double precision NOT NULL CHECK (x >= 0 AND x <= 400),
    y double precision NOT NULL CHECK (y >= 0 AND y <= 400),
    flip boolean NOT NULL DEFAULT false,
    -- Attribution survives the placer leaving; the object does not vanish with
    -- their account.
    created_by uuid REFERENCES users(id) ON DELETE SET NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
);

-- Read pattern is "every object, in paint order", once per map fetch.
CREATE INDEX garden_objects_paint_idx ON garden_objects (y, x);
